name: Build and upload IPA

on:
  push:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build IPA
        run: |
          xcodebuild -project dirtycow.xcodeproj -scheme dirtycow -sdk iphoneos -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -derivedDataPath build
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/dirtycow.app Payload
          zip -r dirtycowapp.ipa Payload
      
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: dirtycowapp
          path: dirtycowapp.ipa